---
title: "Untitled"
author: "Taruki Gunawardana"
date: "2023-10-01"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(ggplot2)
library(visdat)
```

## R Markdown


```{r read csv}
smoking_prev_word <- read.csv("8. Age-standardized estimates of current tobacco use, tobacco smoking and cigarette smoking.csv")
smoking_prev_word
```

## Including Plots


```{r empty columns}
empty_columns <- colSums(is.na(smoking_prev_word) | smoking_prev_word == "") == nrow(smoking_prev_word)
smoking_prev_word_1 <- smoking_prev_word[, !empty_columns]
smoking_prev_word_1
```

```{r removing useless columns}
smoking_prev_word_1$IndicatorCode %>% unique()
smoking_prev_word_1$Indicator %>% unique()
# This shows that indicator code and indicator both show the same thing therefore only keeping one


smoking_prev_word_1$Dim1.type %>% unique
smoking_prev_word_1 %>% filter(Dim1.type == "Sex") %>% summarise(count = n())
# This just gives "Sex" in 8859 rows. so all rows just show Sex - not useful

smoking_prev_word_1 %>% filter(Dim1 == "Both sexes" & Dim1ValueCode == "BTSX") %>% count()
smoking_prev_word_1 %>% filter(Dim1 == "Female" & Dim1ValueCode == "FMLE") %>% count()
smoking_prev_word_1 %>% filter(Dim1 == "Male" & Dim1ValueCode == "MLE") %>% count()
# This shows that these columns show the same thing so excluding one

smoking_prev_word_1 %>% filter(FactValueNumeric != Value)
# This shows that these two columns show the same thing so excluding one of them

smoking_prev_word_2 <- smoking_prev_word_1 %>%
  select(-ValueType, -Location.type, -Period.type, -Indicator, -ParentLocationCode, -SpatialDimValueCode, -Dim1.type, -Dim1ValueCode, -FactValueNumeric, -FactComments, -Language, -DateModified)
smoking_prev_word_2
  
```



```{r separating the estimates}

tobacco_use <- smoking_prev_word_2 %>% filter(IndicatorCode == "M_Est_tob_curr_std") #this is both smoked and smokeless tobacco (this includes cigarettes)
tobacco_smoking <- smoking_prev_word_2 %>% filter(IndicatorCode == "M_Est_smk_curr_std") #smoked tobacco 
cigarette_smoking <- smoking_prev_word_2 %>% filter(IndicatorCode == "M_Est_cig_curr_std") #cigarettes in  particular (not sure if this includes e-cigarettes though?? - probably not)

smoking_prev_word_2 %>% group_by(IndicatorCode) %>% tally() #confirms number of rows correct in each table
```




```{r exploring tobacco use}

types <- tobacco_use %>%
    vis_dat
missing <- tobacco_use %>%
    vis_miss

## no missing values - meaning countries that doesn't have any values are just not in the table

```


```{r plotting tobacco use}

## let's try a random country

plot <- tobacco_use %>% 
  filter(Location == "United States of America") %>%
  ggplot(., mapping = aes(x = Period, y = Value, color = Dim1)) +
  geom_line() +
  geom_point() +
  labs(x = "Year", y = "Estimated prevalence %", title = "Estimate of current tobacco use prevalence(%) (age-standardized rate)")
plot

## let's try all countries 
tobacco_use$Location %>% unique() %>% length() #there are 164 countries 

```



```{r exploring tobacco smoking}

types <- tobacco_smoking %>%
    vis_dat
missing <- tobacco_smoking %>%
    vis_miss

## no missing values - meaning countries that doesn't have any values are just not in the table

```


```{r exploring cigarette smoking}

types <- cigarette_smoking %>%
    vis_dat
missing <- cigarette_smoking %>%
    vis_miss

## no missing values - meaning countries that doesn't have any values are just not in the table

```



